### ISSUE TITLE
Proposal to support native ping pong out of the box

### ISSUE THREAD

**Issue by ogheo** [bminer/ws-server-wrapper#2]
Hi @bminer,

I would like to thank you for this nice repo and to propose to add ping pong out of the box like here:

https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

what you think about that?

**Comment by bminer** [comment]
@ogheo Thanks for reaching out!  And, of course, you are welcome!

I agree... ping/pong is probably something that should be in place.  I thought `ws` handled it automatically.  From what I understand, this is a server-side only thing because browsers will automatically do ping/pong.  I'll submit a quick PR.  Would you be willing and able to review?

**Comment by ogheo** [comment]
Yes, you're right, server send ping and browser respond with pong.

Regarding implementation, it's ok to me and work as expected.

**Comment by bminer** [comment]
Great catch!  Updating the PR now...

**Comment by bminer** [comment]
@ogheo - Were you able to test and ensure that this is working?

**Comment by ogheo** [comment]
@bminer , take a look at https://github.com/bminer/ws-server-wrapper/pull/3#pullrequestreview-218984138

**Comment by bminer** [comment]
@ogheo - Thank you very much for the suggestion and for testing! I have pushed this out in v1.5.0.  Enjoy!
